### PR TITLE
Esperanto wiki-extractor script for Common Voice

### PR DESCRIPTION
**Pull request by stefangrotz**
This commit contains two files necessary to extract around 96k phrases from the esperanto-wikipedia in a way that they can be [used legally for the Common Voice project](https://discourse.mozilla.org/t/extending-our-sentence-collection-capabilities/38783). Other languages like English, German, French and Spanish have already used this and it helped them a lot to get more sentences with a much wider range of vocabulary into the dataset. The script produces around 96 000 sentences,  (128k before deleting repetitions) in [a file like this](https://raw.githubusercontent.com/stefangrotz/common-voice-eo-vikipedio/master/Nov%2019/wiki.eo.sort.txt) with the size of around 5.6 MB. . 

This commit contains two files:
First the a blacklist of words that should not be used:
- The list of disallowed words is produced with the scripts from the readme-file here in this repostitory. I've chosen to exclude all words less frequently used than 80 times in all sentences. 

Second, a rule-file that defines which sentences are valid:
- The rule file excludes most letters that are not part of the Esperanto alphabet, this means that it also excludes the letters y, x, w  and q
- It excludes a lot of Esperanto-abbreviations.
- It also excludes sign-patterns that are extremely unusual for Esperanto but used very often in other languages. (like "the" or "sch")

**Important:** To get this pull-request accepted two or three fluent Esperanto speakers need to analyse [this sample file with 100 random sentences](https://github.com/stefangrotz/common-voice-eo-vikipedio/blob/master/Nov%2019/wiki.eo.sample.txt) from the script and say how high the error rate of this sample is. (grammatical errors and typos) I created and checked several random samples and the error rate alsways was between 5-7/100.

After the extraction is done by the Common Voice team I will clean up the sentence collection manually to further decrease the error rate.

PS: I already did a very similar pull request in september (#49) but I decided to completely rewrite it to make things clearer.

EDIT: for comparison: [here are another 100 random sentences](https://github.com/stefangrotz/common-voice-eo-vikipedio/blob/master/Nov%2019/wiki.eo.sample2.txt)

### CODE REVIEW

**Comment by stefangrotz** [comment]
@bidaian I could use your help here. We talked about this in my last pull request in September (#49) Could you review the 100 sample sentences and tell me how many of them wrong in any way?

**Comment by ranulo** [comment]
Hi,
I looked through the 100 sentences and ignored some minor errors like non-closing quotation marks and focussed on grammar and that they are readable for common speakers.  The error rate is pretty good, I would say less than 5%.

**Comment by ianomo** [comment]
Hello I used the second example file. Most errors are simply foreign words. I consider these six sentences not suitable for the project:

> La insulo estas posedo de la National Trust.
> Li estis ano de Hungara Scienca Akademio kaj li ricevis ekzemple premion Kossuth.
> Same kiel Recife la karnavalo havas tre demokratan kaj popularan karakteron.
> Li okupiĝis ekzemple pri "Claviceps purpurea".
> Li konis tie inter aliaj Edith Stein.
> Li komencis konstrui alian grandan teatron, kiun oni nun nomas "Ŝĉukin-a sceno".

**Comment by stefangrotz** [comment]
Hey @nukeador is this enough for you to merge? 

The extraction took around 3h on my device (8GB Ram, 2,6 GHz 6-Core Intel Core i7). It would be great if you would find the time to extract this in the next weeks so I can clean the dataset afterwards and start a little campaign in the esperanto world in january.

**Comment by nukeador** [comment]
merged, now I'll put this in the queue to get executed when we have some engineering time.

We can't commit to a specific date but I'll try to get this done before EOY.

**Comment by stefangrotz** [comment]
Hey @nukeador just for my personal time management: do you think that the extraction will happen before EOY or should I plan with some date in January?

**Comment by nukeador** [comment]
Hi,

Having in mind the holiday break, I don't expect we'll have time for this until at least the first week of January, sorry for that.

Thanks for your patience!

**Comment by stefangrotz** [comment]
Okay good to know. I [prepared some promo material ](https://github.com/stefangrotz/common-voice-work-files/tree/master/Esperanto/promo%20material) (social media banners, one-page adds) and contacted some Esperanto magazines and organizations and clubs and start a little campaign in February.  I want to have a few weeks to clean the sentences, so the second week of January would be great for me.

**Pull request merged**
