### PR TITLE
Italian rules updated

### PR DESCRIPTION
**Pull request by Mte90**
I am working to improve the blacklist but I saw this parameters that can be improved.

### CODE REVIEW

**Comment by MichaelKohler** [comment]
The broken whitespace and min characters changes look good to me. What data is the maximum words based on? Would love to hear more about that :)

**Comment by Mte90** [comment]
Italian has sentences with more words then other languages, I saw also that sometimes are shorts so it was a workaround for that.

**Comment by MichaelKohler** [comment]
@nukeador any thoughts on the word count increase? The rest looks good to me.

**Comment by nukeador** [comment]
As long as the resulting sentences take less than 10s to read, we should be fine.

**Comment by MichaelKohler** [comment]
@Mte90 can you confirm? If so, I'll merge

**Comment by Mte90** [comment]
Yes I can confirm :-)

**Pull request merged**
